name: ml
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scipy
  - statsmodels
  - plotly
  - scikit-learn
  - fbprophet
  - seaborn
  - pip:
    - beautifulsoup4==4.8.1
    - lxml==4.4.1 
    - pmdarima==1.4.0

  
