name: ml
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scipy
  - statsmodels
  - pmdarima
  - plotly
  - chart_studio
  - scikit-learn
  - fbprophet
  - pip:
    - beautifulsoup4==4.8.1
    - lxml==4.4.1 

  
